export interface Tactic {
  number: number;
  name: string;
  description: string;
  phase: string[];
  risk: "baixo" | "medio" | "alto";
  whenToUse: string;
  example: string;
}

export const TACTICS: Tactic[] = [
  { number: 1, name: "Escolha o Alvo Certo", description: "Identifique quem está mais receptivo e vulnerável ao seu tipo de sedução.", phase: ["lead_generation"], risk: "baixo", whenToUse: "No início, ao escolher em quem investir energia.", example: "Observe quem demonstra sinais de carência emocional ou busca por novidade." },
  { number: 2, name: "Crie uma Falsa Sensação de Segurança", description: "Aproxime-se como amigo/confidente antes de revelar interesse. Baixe as defesas.", phase: ["lead_generation", "qualification"], risk: "baixo", whenToUse: "Quando o alvo é desconfiado ou tem barreiras altas.", example: "Comece com conversas casuais sem flertar. Seja a pessoa com quem o alvo se sente à vontade." },
  { number: 3, name: "Envie Sinais Mistos", description: "Alterne entre demonstrar interesse e recuar, criando confusão e obsessão.", phase: ["qualification", "nurturing"], risk: "medio", whenToUse: "Quando a dinâmica está ficando previsível.", example: "Depois de uma conversa intensa, fique um dia sem responder. Retorne como se nada tivesse acontecido." },
  { number: 4, name: "Apareça como Objeto de Desejo", description: "Faça o alvo perceber que outras pessoas te desejam. Crie competição social.", phase: ["qualification", "nurturing"], risk: "medio", whenToUse: "Quando o alvo parece acomodado ou pouco investido.", example: "Poste fotos sociais com outras pessoas atraentes. Mencione casualmente convites que recebeu." },
  { number: 5, name: "Crie Necessidade", description: "Torne-se indispensável preenchendo um vazio emocional específico do alvo.", phase: ["nurturing"], risk: "baixo", whenToUse: "Após identificar a vulnerabilidade principal.", example: "Se o alvo se sente intelectualmente subestimado, seja quem reconhece e estimula sua inteligência." },
  { number: 6, name: "Domine a Arte da Insinuação", description: "Sugira sem dizer explicitamente. Deixe a imaginação do alvo fazer o trabalho.", phase: ["qualification", "nurturing"], risk: "baixo", whenToUse: "Quando quer criar tensão sexual sem ser direto demais.", example: "Use duplo sentido sutil, pausas estratégicas e olhares que dizem mais que palavras." },
  { number: 7, name: "Entre no Espírito do Alvo", description: "Espelhe valores, gostos e estilo de comunicação. Crie sensação de alma gêmea.", phase: ["nurturing"], risk: "baixo", whenToUse: "Quando quer aprofundar a conexão emocional.", example: "Adote temporariamente interesses do alvo. Use o mesmo estilo de mensagem (emojis, tamanho, tom)." },
  { number: 8, name: "Crie Tentação", description: "Ofereça vislumbres do que poderia ser, mas não entregue tudo. Mantenha o mistério.", phase: ["nurturing", "closing"], risk: "medio", whenToUse: "Quando o alvo está investido mas você quer manter controle.", example: "Planeje um encontro especial, dê detalhes vagos. Faça o alvo antecipar e fantasiar." },
  { number: 9, name: "Mantenha o Suspense", description: "Nunca seja totalmente previsível. Surpreenda com ações inesperadas.", phase: ["nurturing", "retention"], risk: "baixo", whenToUse: "Quando a dinâmica está ficando rotineira.", example: "Mude planos de última hora para algo melhor. Apareça em um lugar inesperado." },
  { number: 10, name: "Use o Poder das Palavras", description: "Domine a comunicação verbal — elogios estratégicos, histórias envolventes, humor calibrado.", phase: ["qualification", "nurturing", "closing"], risk: "baixo", whenToUse: "Em toda conversa significativa.", example: "Elogie algo específico e não óbvio. Conte histórias com arco emocional que revelam vulnerabilidade calculada." },
  { number: 11, name: "Preste Atenção aos Detalhes", description: "Lembre de coisas pequenas que o alvo mencionou. Demonstre que você realmente escuta.", phase: ["nurturing", "closing"], risk: "baixo", whenToUse: "Para criar sensação de conexão profunda.", example: "Mencione um detalhe de uma conversa de semanas atrás. Traga algo que o alvo disse que gosta." },
  { number: 12, name: "Poetize sua Presença", description: "Transforme momentos comuns em experiências memoráveis e cinematográficas.", phase: ["nurturing", "closing"], risk: "baixo", whenToUse: "Em encontros presenciais para maximizar impacto.", example: "Escolha locais com atmosfera especial. Crie rituais únicos entre vocês." },
  { number: 13, name: "Desarme com Vulnerabilidade Estratégica", description: "Mostre uma fraqueza calculada para criar intimidade e confiança.", phase: ["nurturing", "closing"], risk: "medio", whenToUse: "Quando quer quebrar barreiras emocionais do alvo.", example: "Compartilhe um medo ou insegurança real (mas não devastadora). Mostre humanidade." },
  { number: 14, name: "Confunda Desejo com Realidade", description: "Faça o alvo projetar suas fantasias em você, tornando-se tela para os desejos dele.", phase: ["nurturing"], risk: "medio", whenToUse: "Quando já conhece as fantasias e desejos do alvo.", example: "Adote temporariamente o papel que o alvo idealiza. Seja a versão que ele procura." },
  { number: 15, name: "Isole o Alvo", description: "Crie um mundo de dois — afaste influências externas que poderiam sabotar.", phase: ["nurturing", "closing"], risk: "alto", whenToUse: "Quando amigos ou família do alvo são obstáculos.", example: "Sugira programas a dois em vez de grupo. Crie experiências privadas e exclusivas." },
  { number: 16, name: "Prove seu Valor", description: "Demonstre habilidades, conquistas ou qualidades em ação, não em palavras.", phase: ["qualification", "nurturing"], risk: "baixo", whenToUse: "Quando quer elevar sua percepção de valor.", example: "Em vez de dizer que cozinha bem, convide para jantar na sua casa e surpreenda." },
  { number: 17, name: "Execute o Recuo Estratégico", description: "Afaste-se temporariamente para criar saudade e valorização.", phase: ["nurturing", "closing"], risk: "alto", whenToUse: "Quando o alvo está muito confortável ou tomando você como garantido.", example: "Fique 24-48h sem contato. Quando retornar, aja normalmente sem dar explicações." },
  { number: 18, name: "Estimule a Transgressão", description: "Incentive o alvo a quebrar pequenas regras ou sair da zona de conforto.", phase: ["nurturing", "closing"], risk: "medio", whenToUse: "Quando quer criar cumplicidade e adrenalina.", example: "Proponha algo levemente ousado que o alvo normalmente não faria." },
  { number: 19, name: "Use o Toque Físico Estratégico", description: "Escale contato físico gradualmente para criar intimidade e tensão.", phase: ["closing"], risk: "medio", whenToUse: "Em encontros presenciais com boa receptividade.", example: "Toque no braço ao rir, ajuste o cabelo, proximidade física gradual." },
  { number: 20, name: "Crie Momentos de Tensão", description: "Construa anticipação e desejo através de pausas, silêncios e almost-moments.", phase: ["closing"], risk: "medio", whenToUse: "Antes do movimento ousado final.", example: "Olhar prolongado seguido de pausa. Aproxime-se mas recue no último momento." },
  { number: 21, name: "Inicie o Recuo Estratégico", description: "Recue completamente após um pico emocional para maximizar o impacto.", phase: ["nurturing", "closing"], risk: "alto", whenToUse: "Após um momento muito intenso entre vocês.", example: "Após um encontro incrível, não envie mensagem por 24h. Deixe o alvo processar." },
  { number: 22, name: "Use o Triângulo", description: "Introduza um terceiro elemento (real ou imaginário) para despertar ciúmes controlados.", phase: ["nurturing"], risk: "alto", whenToUse: "Quando o alvo está perdendo interesse ou muito seguro de si.", example: "Mencione casualmente alguém interessante que conheceu. Não exagere." },
  { number: 23, name: "Execute o Movimento Ousado", description: "Tome uma ação decisiva e confiante que mude o jogo definitivamente.", phase: ["closing"], risk: "alto", whenToUse: "Quando todos os sinais indicam receptividade máxima.", example: "Declaração direta, beijo, convite ousado. Confiança é a chave." },
  { number: 24, name: "Domine os Pós-Efeitos", description: "Após a conquista, mantenha a dinâmica viva com variação e interesse renovado.", phase: ["retention"], risk: "baixo", whenToUse: "Após alcançar o objetivo principal.", example: "Continue surpreendendo. Nunca fique 100% previsível ou disponível." },
];

export const RISK_COLORS = {
  baixo: "#059669",
  medio: "#d97706",
  alto: "#e11d48",
};
